site_name: liquidpy
theme:
    name: 'material'
    font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.extra
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
extra_css:
    - 'extra.css'
nav:
    - 'Home': 'index.md'
    - 'Introduction': 'intro.md'
    - 'White space control': 'wscontrol.md'
    - 'Debug': 'debug.md'
    - 'Nodes': 'nodes.md'
    - 'Inheritance and inclusion': 'extends_include.md'
    - 'Filters': 'filters.md'
    - 'Modifiers': 'modifiers.md'
    - 'Change log': 'changelog.md'
    - 'API': 'api.md'
