[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "liquidpy"
version = "0.8.6"
description = "A port of liquid template engine for python"
authors = [{ name = "pwwang", email = "pwwang@pwwang.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "jinja2>=3,<4",
]

[project.urls]
Homepage = "https://github.com/pwwang/liquidpy"
Repository = "https://github.com/pwwang/liquidpy"

[project.optional-dependencies]
extra = [
    "python-frontmatter>=1.0",
    "markdown>=3.4; python_version < '3.8'",
    "markdown>=3.5; python_version >= '3.8'",
    "regex>=2023.12; python_version < '3.8'",
    "regex>=2024.11; python_version >= '3.8'",
    "python-slugify>=8",
    "python-dateutil>=2.8",
    # needed by python-frontmatter
    "toml>=0.10",
]

[dependency-groups]
dev = [
    "pytest>=7",
    "pytest-cov>=4",
    "six>=1.17",
]
docs = [
    "mkapi-fix>=0.1.1",
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.2.6",
    "pymdown-extensions>=10.2.1",
]

[tool.hatch.build.targets.wheel]
packages = ["liquid"]

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'

[tool.pytest.ini_options]
addopts = "-vv -p no:asyncio --cov-config=.coveragerc --cov=liquid --cov-report xml:cov.xml --cov-report term-missing"
console_output_style = "progress"
junit_family = "xunit1"

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
disable_error_code = ["attr-defined", "no-redef", "union-attr"]
show_error_codes = true
strict_optional = false
