name: docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v6
      - name: Set up uv and Python (${{ matrix.python-version }})
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --group docs
      - name: Build docs
        run: |
          cd docs
          cp ../README.md index.md
          cd ..
          uv run mkdocs build
        if : success()
      - name: Deploy docs
        run: |
          uv run mkdocs gh-deploy --clean --force
        if: success() && (github.ref == 'refs/heads/master' || contains(github.event.head_commit.message, '[docs]'))
